spring.application.name=Enchere

# application.properties
spring.mvc.hiddenmethod.filter.enabled=true

#Profil actif
spring.profiles.active=mysql

# Param bdd
spring.datasource.url=jdbc:mysql://localhost:3306/enchere
spring.datasource.username=root
spring.datasource.password=

# Durée de la session (par défaut 5 minutes)
server.servlet.session.timeout=5m